### PR TITLE
Add RPATH support

### PR DESCRIPTION
**Pull request by claudiofantacci**
This PR aims to cover RPATH support as a followup of issue #48.

I have added `AddInstallRPATHSupport.cmake` from YCM and used it accordingly in the `CMakeLists.txt`.

### CODE REVIEW

**Comment by claudiofantacci** [comment]
Travis macOS tests failed because of `Error: No available formula with the name "yarp"`, while Linux tests failed due to ` Optional package Eigen3 not found.`.

We have to modify the `travis.yml` to account this issues.

**Comment by francesco-romano** [comment]
Let's wait for https://github.com/robotology/robot-testing/pull/50 to relaunch the build

**Comment by francesco-romano** [comment]
https://github.com/robotology/robot-testing/pull/50 merged.
I relaunch the travis build.

**Comment by claudiofantacci** [comment]
It seems that Travis is failing with the same errors.

**Comment by francesco-romano** [comment]
Because I'm stupid and I did not rebase the branch

**Comment by claudiofantacci** [comment]
Eheh no worries!

**Comment by claudiofantacci** [comment]
Rebased on master 👍

**Pull request merged**
