### PR TITLE
Added simple test for FT sensors.

### PR DESCRIPTION
**Pull request by francesco-romano**
Only port connection and vector size is checked.

### CODE REVIEW

**Comment by traversaro** [comment]
+1

**Comment by traversaro** [comment]
Merging, but I guess we should find a systematic way of dealing with icubSim/icub/icubGazeboSim in the name of the robots.

**Comment by lornat75** [comment]
I addition I think we have to separate config files for the different cases: icub, icubSim and iCubGazeboSim (real, ode and gazebo). I don't think the ode simulator has F/T sensors...

**Comment by lornat75** [comment]
If we do so we could dodge the problem by changing robot name in all files. OR we could just always use icub and change the name of the ports opened by the simulators (in the ode simulator it can be done from command line).

**Comment by francesco-romano** [comment]
I agree.
Also we should "pass" the command line arguments to the test classes: e.g. `--robot`, so the `portname` option can become a suffix.

**Comment by traversaro** [comment]
Agreed, but we should not encode the port naming rules logic in the tests: we do that in device wrappers but those behaviour is often undocumented and confusing to the end user. I really like the idea of using variable expansions, for example the test files for the ft sensors would become, from this:
```
name "Test FT sensors Left Arm"
portname /icubGazeboSim/left_arm/analog:o
```

to this
```
name "Test FT sensors Left Arm"
portname /${robot}/left_arm/analog:o
```

**Comment by lornat75** [comment]
Done in: https://github.com/robotology/robot-testing/pull/5

**Pull request merged**
