### PR TITLE
Fix suit -> suite

### PR DESCRIPTION
**Pull request by drdanz**
### Warning: breaking change

I don't think it is worth supporting both the **suit** and **suite** syntax in the xml parsing and in the arguments, it would require a lot of effort just to support a typo. I suggest we just break compatibility now instead.

in master we can ensure that the RTF version is ok by changing:

```diff
-find_package(RTF 1.2)
+find_package(RTF 1.2 EXACT)
```

in devel we can change it to
```diff
-find_package(RTF 1.2)
+find_package(RTF 1.3)
```

### CODE REVIEW

**Comment by traversaro** [comment]
Fix https://github.com/robotology/robot-testing/issues/47 .

**Comment by traversaro** [comment]
I hate to always be the "backwards compatibility" guy, but the amount of tests that we have in the [vvv-school repository](https://github.com/vvv-school) and the students' forked repositories in my opinion call for a proper tick-tock cycle of deprecation/removal.

**Comment by pattacini** [comment]
I would go for the smoothest change possible.

**Comment by pattacini** [comment]
Please trigger me once merged so that I'll take care of updating vvv-school.

**Comment by traversaro** [comment]
Support and tests for the legacy options added in https://github.com/robotology/robot-testing/pull/71/commits/3dd861e61347dae6b9a8899d0618821fc805b2bc .

**Comment by drdanz** [comment]
Thanks @traversaro for supporting the legacy option... I think we can merge this now since it's no longer breaking icub-tests and vvv-school... anyone against merging?

**Comment by aerydna** [comment]
merged, thanks!

**Pull request merged**
