### PR TITLE
[yarp] commited first support for middleware specific yarp files

### PR DESCRIPTION
**Pull request by traversaro**
YARP support can be enabled during RTF compilation using the `ENABLE_YARP` CMake option.

If a user wants to check if RTF is build with YARP support, he can check against the `YARP` CMake component of RTF, as in:
`find_package(RTF 1.0.1 COMPONENTS YARP REQUIRED)`

Bump the version number to 1.0.1 . 

Overall the scheme followed is the same of the Lua/Python/Ruby support, to enable in the future support for other robot middlewares (ROS, Orocos, etc etc).

### CODE REVIEW

**Comment by traversaro** [comment]
cc @apaikan

**Comment by apaikan** [comment]
@traversaro  Well done! 

a comment: can we remove the YARP find package from the main CMAKE and put it under the src/middleware?  and  keep the ENABLE_YARP  option in the main CMAKE to enable it


# middleware specific options
find_package(YARP)
# automatically build YARP integration if yarp is found
option (ENABLE_YARP "Enable yarp integration" ${YARP_FOUND})

**Comment by traversaro** [comment]
done!

**Comment by traversaro** [comment]
But probably I missed what you meant with "and keep the ENABLE_YARP option in the main CMAKE to enable it"

**Comment by apaikan** [comment]
Thanks. I meant if you still want to automatically enable YARP, we can have an option in the main Cmake for enabling the middleware dependent codes, something like 

```
option (ENABLE_MIDDLEWARE_PLUGINS) "Enable middleware dependent plugins" OFF) 
``` 

Then, if this is enabled, all the cmakes from the the src/middleware are called and automatically got enabled if, for example, YARP is found. However, It's better we keep the `ENABLE_MIDDLEWARE_PLUGINS` OFF by default.

**Comment by traversaro** [comment]
Ahh... ok. Actually the purpose of auto-enabling the YARP options was meant to simplify installation of RTF for yarp users that can install it without setting any configuration option.. adding an additional `ENABLE_MIDDLEWARE_PLUGINS` option actually complexities this, but if it's better to keep it off by default it's ok.

**Comment by traversaro** [comment]
ENABLE_MIDDLEWARE_PLUGINS option added.

**Comment by traversaro** [comment]
Conflict with ruby stuff manually solved.

**Pull request merged**
